# -*- coding: utf-8 -*-
"""AnalyzingHospitalData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pPbJbZ5IdIQgzzJskTxMLJvcaQ9dgQY5
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

data = pd.read_csv('Hospital_dataset.csv')

data.head()

X = data.iloc[:,:-1].values
y = data.iloc[:, -1].values

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, train_size = 0.70, random_state = 1)

print("Shape of X_train " + str(X_train.shape))
print("Shape of X_test " + str(X_test.shape))
print("Shape of y_train " + str(y_train.shape))
print("Shape of y+test " + str(y_test.shape))

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import math

Lmodel = LinearRegression()

model = Lmodel.fit(X_train, y_train)

pred_train = model.predict(X_train)

print(math.sqrt(mean_squared_error(y_train, pred_train)))

pred_test = model.predict(X_test)
print(math.sqrt(mean_squared_error(y_test, pred_test)))

