# -*- coding: utf-8 -*-
"""LogisticRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FZQ9RAbTOILmn2kjqnsvLkcMHiciQnmm
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

data = datasets.load_digits()

dir(data)

plt.gray()
plt.matshow(data.images[200])
plt.show()

data.target[200]

data.data.shape

X, y = data.data, data.target
print(X.shape)
print(y.shape)

np.unique(y)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, train_size=0.80, random_state=1)

print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

from sklearn import linear_model

LoR = linear_model.LogisticRegression(multi_class='ovr', solver='liblinear')
model = LoR.fit(X_train, y_train)

X_test[20].reshape(1,-1).shape

X_test[160].reshape(8,8).shape

print("Prediction of the given input image " + str(model.predict(X_test[160].reshape(1,-1))))

print("THe Ground Truth digit is: ")

plt.gray()
plt.matshow(X_test[210].reshape(8,8))
plt.show()



import numpy as np
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

dir(data)